import {
  POSE_LANDMARKS,
  POSE_LANDMARKS_LEFT,
  POSE_LANDMARKS_RIGHT,
} from '@mediapipe/pose';
import * as THREE from 'three';

export const MAX_POSE_INDEX = 32;
export const MID_SHOULDER = MAX_POSE_INDEX + 1;
export const MID_HIP = MAX_POSE_INDEX + 2;
export const MID_FOOT_INDEX = MAX_POSE_INDEX + 3;

export const MY_LEFT_POSEINDEX = [
  POSE_LANDMARKS_LEFT.LEFT_SHOULDER,
  POSE_LANDMARKS_LEFT.LEFT_HIP,
  POSE_LANDMARKS_LEFT.LEFT_HEEL,
  POSE_LANDMARKS_LEFT.LEFT_FOOT_INDEX,
];
export const MY_RIGHT_POSEINDEX = [
  POSE_LANDMARKS_RIGHT.RIGHT_SHOULDER,
  POSE_LANDMARKS_RIGHT.RIGHT_HIP,
  POSE_LANDMARKS_RIGHT.RIGHT_HEEL,
  POSE_LANDMARKS_RIGHT.RIGHT_FOOT_INDEX,
];
export const MY_NEUTRAL_POSEINDEX = [MID_HIP, MID_SHOULDER, MID_FOOT_INDEX];

export const MY_ALL_POSEINDEX = MY_LEFT_POSEINDEX.concat(
  MY_RIGHT_POSEINDEX,
  MY_NEUTRAL_POSEINDEX
);

export const MY_NEUTRAL_POSE_CONNECTIONS: Array<[number, number]> = [
  // [POSE_LANDMARKS.LEFT_EYE, POSE_LANDMARKS.RIGHT_EYE],
  [POSE_LANDMARKS_LEFT.LEFT_SHOULDER, POSE_LANDMARKS_RIGHT.RIGHT_SHOULDER],
  [POSE_LANDMARKS_LEFT.LEFT_HIP, POSE_LANDMARKS_RIGHT.RIGHT_HIP],
  [POSE_LANDMARKS_LEFT.LEFT_FOOT_INDEX, POSE_LANDMARKS_RIGHT.RIGHT_FOOT_INDEX],
];
export const MY_LEFT_POSE_CONNECTIONS: Array<[number, number]> = [
  [POSE_LANDMARKS_LEFT.LEFT_EYE, POSE_LANDMARKS.NOSE],
  [POSE_LANDMARKS_LEFT.LEFT_SHOULDER, POSE_LANDMARKS_LEFT.LEFT_ELBOW],
  [POSE_LANDMARKS_LEFT.LEFT_ELBOW, POSE_LANDMARKS_LEFT.LEFT_WRIST],
  [POSE_LANDMARKS_LEFT.LEFT_SHOULDER, POSE_LANDMARKS_LEFT.LEFT_HIP],
  [POSE_LANDMARKS_LEFT.LEFT_HIP, POSE_LANDMARKS_LEFT.LEFT_KNEE],
  [POSE_LANDMARKS_LEFT.LEFT_KNEE, POSE_LANDMARKS_LEFT.LEFT_ANKLE],
  [POSE_LANDMARKS_LEFT.LEFT_ANKLE, POSE_LANDMARKS_LEFT.LEFT_HEEL],
  [POSE_LANDMARKS_LEFT.LEFT_HEEL, POSE_LANDMARKS_LEFT.LEFT_FOOT_INDEX],
];
export const MY_RIGHT_POSE_CONNECTIONS: Array<[number, number]> = [
  [POSE_LANDMARKS_RIGHT.RIGHT_EYE, POSE_LANDMARKS.NOSE],
  [POSE_LANDMARKS_RIGHT.RIGHT_SHOULDER, POSE_LANDMARKS_RIGHT.RIGHT_ELBOW],
  [POSE_LANDMARKS_RIGHT.RIGHT_ELBOW, POSE_LANDMARKS_RIGHT.RIGHT_WRIST],
  [POSE_LANDMARKS_RIGHT.RIGHT_SHOULDER, POSE_LANDMARKS_RIGHT.RIGHT_HIP],
  [POSE_LANDMARKS_RIGHT.RIGHT_HIP, POSE_LANDMARKS_RIGHT.RIGHT_KNEE],
  [POSE_LANDMARKS_RIGHT.RIGHT_KNEE, POSE_LANDMARKS_RIGHT.RIGHT_ANKLE],
  [POSE_LANDMARKS_RIGHT.RIGHT_ANKLE, POSE_LANDMARKS_RIGHT.RIGHT_HEEL],
  [POSE_LANDMARKS_RIGHT.RIGHT_HEEL, POSE_LANDMARKS_RIGHT.RIGHT_FOOT_INDEX],
];
export const MY_ALL_POSE_CONNECTIONS = MY_LEFT_POSE_CONNECTIONS.concat(
  MY_RIGHT_POSE_CONNECTIONS,
  MY_NEUTRAL_POSE_CONNECTIONS
);

export const COLOR_LEFT = new THREE.Color(0xffa500);
export const COLOR_RIGHT = new THREE.Color(0x00d9e7);
export const COLOR_NEUTRAL = new THREE.Color(0xffffff);
